name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Check for changes
        id: check-changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: 📂 Sync files
        if: steps.check-changes.outputs.changed_files != ''
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ilkomerz.biz.id
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          exclude: .htaccess
